name: Gatsby Publish

on:
  push:
    branches:
      - publish

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.OTHER_ACCESS_TOKEN }}
          deploy-branch: gh-pages

          # Use this param if the site isn't going to be hosted at the root level of the domain
          # gatsby-args: '--prefix-paths'
